### PR TITLE
Circle build

### PR DESCRIPTION
**Pull request by drorg**

### CODE REVIEW

**Comment by itayvallach** [comment]
💯

**Comment by itayvallach** [comment]
:)))

**Comment by lomudi** [comment]
@itayvallach should we meet for a coffee? :)

**Comment by drorg** [comment]
@itayvallach be careful from @lomudi , he brought back mr. tzarfati

**Comment by itayvallach** [comment]
@drorg I don't believe you..
@lomudi before our coffee you should do some security checks to see why ex-employees have access to your repos ;)

**Comment by lomudi** [comment]
@itayvallach it's an open repo, not a close one and we love to get your review any time.
and believe @drorg ...

**Review by reuvenlevitsky — APPROVED** [review]

**Pull request merged**
